"""add devflow release observations

Revision ID: 2efd11889b72
Revises: 21b054f993dd
Create Date: 2026-09-11 23:56:02.829234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2efd11889b72"
down_revision: str | Sequence[str] | None = "21b054f993dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.String(length=120), nullable=False),
        sa.Column(
            "source", sa.String(length=40), server_default="devflow", nullable=False
        ),
        sa.Column("source_pipeline_run_id", sa.UUID(), nullable=False),
        sa.Column("source_deployment_id", sa.UUID(), nullable=True),
        sa.Column("environment", sa.String(length=100), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("image_reference", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("raw_event", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'rolled_back')",
            name="ck_release_observations_status",
        ),
        sa.CheckConstraint(
            "length(commit_sha) = 40", name="ck_release_observations_commit_sha"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id"),
    )
    op.create_index(
        "ix_release_observations_service_time",
        "release_observations",
        ["service_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_release_observations_service_time", table_name="release_observations"
    )
    op.drop_table("release_observations")
    # ### end Alembic commands ###
