"""add release recommendation and approval

Revision ID: b4ff2337f90f
Revises: 2efd11889b72
Create Date: 2026-09-12 00:08:59.370234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4ff2337f90f"
down_revision: str | Sequence[str] | None = "2efd11889b72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("release_status", sa.String(length=30), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=True),
        sa.Column(
            "error_budget_burn_rate", sa.Numeric(precision=14, scale=6), nullable=True
        ),
        sa.Column("slo_breached", sa.Boolean(), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column(
            "human_approval_required",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "automated_mutation_allowed",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('proceed', 'manual_review', 'block')",
            name="ck_release_recommendations_decision",
        ),
        sa.CheckConstraint(
            "automated_mutation_allowed = false",
            name="ck_release_recommendations_no_mutation",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["release_observations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "observation_id", name="uq_release_recommendations_observation"
        ),
    )
    op.create_table(
        "release_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name="ck_release_approvals_decision"
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["release_recommendations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id", name="uq_release_approvals_recommendation"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_approvals")
    op.drop_table("release_recommendations")
    # ### end Alembic commands ###
